### ISSUE TITLE
[ioc] bean lifecycle

### ISSUE THREAD

**Issue by Alice52** [Alice52/java-ocean#116]
### [bean lifecycle](https://mp.weixin.qq.com/s?__biz=MzA4NzQ0Njc4Ng==&mid=2247485221&idx=2&sn=7a5f2de28240f496572d855e6861bbf6)

- **bean create -- bean init[`对象创建完成且赋值好之后`] -- use -- destroy**

  - singleton:
    - init: 容器创建时创建对象, 并调用 Init() 方法
    - destroy: 容器关闭时调用
  - prototype:
    - init: 第一次使用时才会创建对象, 并调用 Init() 方法
    - destroy: 容器只会创建这个 Bean 但是不会销毁[管理], 如果需要则自己手动销毁

1. BeanPostProcessor
    ```java
    BeanPostProcessor

    populateBean(beanName, mbd, instanceWrapper); // set value of bean
    initializeBean
    {
       applyBeanPostProcessorsBeforeInitialization(wrappedBean, beanName);
       invokeInitMethods(beanName, wrappedBean, mbd); // execute custom init
       applyBeanPostProcessorsAfterInitialization(wrappedBean, beanName);
   }
   ```

2. **`@PostConstruct && @PreDestroy`**
3. **InitializingBean && DisposableBean**
4. `@Bean(value = "person", initMethod = "init", destroyMethod = "destroy")`

**Comment by Alice52** [comment]
#115 ioc inject

#67  sequence of component

**Comment by Alice52** [comment]
1. BeanDefinitionRegistryPostProcessor
2. BeanFactoryPostProcessor
3. BeanPostProcessor#postProcessBeforeInitialization
4. @PostConstruct
5. InitializingBean#afterPropertiesSet
6. @Bean#init
7. BeanPostProcessor#postProcessAfterInitialization
8. @PreDestroy
9. DisposableBean#destroy
10. @Bean#destroy

**Comment by Alice52** [comment]
## BeanDefinition: `BeanDefinition + DefaultResourceLoader + XmlBeanDefinitionReader + BeanDefinitionRegister +  `

1. bean xml node 上的 id 和 name 是帮助注册到 bean 的注册中心[BeanDefinitionRegistry extends AliasRegistry]

    ![spring-ioc-bean](https://user-images.githubusercontent.com/42330329/87787090-a8f76f00-c86d-11ea-888b-2fdd17f03ed9.png)
   
    ```java
   // beanName is value of id, and in BeanDefinitionRegistry
   // 一个 id 只能有一个 bean, 但是一个bean可以有多个 id
   // 所以通过别名[name 属性]去获取 BeanDefinition 是不可以的
   // 没有写 ID 的则会默认使用 全类名#index 作为 id
   void registerBeanDefinition(String beanName, BeanDefinition beanDefinition) throws BeanDefinitionStoreException;


   // name in AliasRegistry
   void registerAlias(String name, String alias);
   ```

2. xml --> BeanDefinition --> BeanDefinitionRegister

![spring-ioc-bean-definition](https://user-images.githubusercontent.com/42330329/87787135-bad91200-c86d-11ea-8a77-df3bb25890a4.png)

**Comment by Alice52** [comment]
### BeanFactory

![spring-ioc-bean-factory](https://user-images.githubusercontent.com/42330329/87787362-14414100-c86e-11ea-9458-74e6847fd3ae.png)


![spring-ioc-factory](https://user-images.githubusercontent.com/42330329/87787384-1f946c80-c86e-11ea-97d6-45b5a526422d.png)


```log
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at cn.edu.ntu.javaee.spring.common.entity.Person.<init>(Person.java:43)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-1)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:200)
	  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$7.171802996.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	  - locked <0x6e0> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	  at cn.edu.ntu.javaee.spring.ioc.BeanDefinitionReaderSample2.main(BeanDefinitionReaderSample2.java:28)
```

![spring-bean-create](https://user-images.githubusercontent.com/42330329/87787417-2de28880-c86e-11ea-9c20-f9f4ec2e292d.png)



![spring-ioc-bean-create-flow](https://user-images.githubusercontent.com/42330329/87787439-376bf080-c86e-11ea-96a7-4b545401085b.png)

1. beanfactory 和 applicationContext 的区别

![spring-ioc-application-context](https://user-images.githubusercontent.com/42330329/87787471-4652a300-c86e-11ea-9663-467429806b6e.png)


   - applicationContext 具有 beanFactory 的所有功能
   - 还有 MessageSource 国际化的消息访问
   - 资源访问: URL + 文件
   - 事件传播: ApplicaitionListener
   - 载入多个有继承关系的上下文, 使的每个上下文都专注于自己的层次, 如 web 层

**Comment by Alice52** [comment]
1. beanfactory 和 applicationContext 的区别
   - applicationContext 具有 beanFactory 的所有功能
   - 还有 MessageSource 国际化的消息访问
   - 资源访问: URL + 文件
   - 事件传播: ApplicaitionListener
   - 载入多个有继承关系的上下文, 使的每个上下文都专注于自己的层次, 如 web 层

![spring-ioc-application-context](https://user-images.githubusercontent.com/42330329/87787471-4652a300-c86e-11ea-9663-467429806b6e.png)
